[package]
name = "precise"
version = "0.1.0"
edition = "2021"

[dependencies]
astro-float = "0.6.8"
dyn-clone = "1.0.11"
nom = "7.1.3"
serde = { version = "1.0.160", features = ["derive"] }
lazy_static = "1.4.0"
